namespace Qlik.Resources
{
    #region Usings
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Text;
    #endregion

    public class CompilerGenerated: IDisposable
    {
        TextWriter tw;
        public CompilerGenerated(string filename, string className)
        {            
            var startText =
"//------------------------------------------------------------------------------                                                                  \r\n"
+ "// <auto-generated>                                                                                                                             \r\n  "
+ "//     Dieser Code wurde von einem Tool generiert.                                                                                              \r\n  "
+ "//     Laufzeitversion:4.0.30319.42000                                                                                                          \r\n  "
+ "//                                                                                                                                              \r\n  "
+ "//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn                                                \r\n  "
+ "//     der Code erneut generiert wird.                                                                                                          \r\n  "
+ "// </auto-generated>                                                                                                                            \r\n  "
+ "//------------------------------------------------------------------------------                                                                \r\n  "
+ "                                                                                                                                                \r\n  "
+ "    namespace Qlik.Resources                                                                                                     \r\n  "
+ "    {                                                                                                                                           \r\n  "
+ "        using System;                                                                                                                           \r\n  "
+ "                                                                                                                                                \r\n  "
+ "                                                                                                                                                \r\n  "
+ "        /// <summary>                                                                                                                           \r\n  "
+ "        ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.                                            \r\n  "
+ "        /// </summary>                                                                                                                          \r\n  "
+ "        // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert                                                        \r\n  "
+ "        // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.                                                           \r\n  "
+ "        // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen                                \r\n  "
+ "        // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.                                                               \r\n  "
+ "        [global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"System.Resources.Tools.StronglyTypedResourceBuilder\", \"15.0.0.0\")]          \r\n     "
+ "        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]                                                                             \r\n  "
+ "        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]                                                                  \r\n  "
+ "        public class "+ className + "                                                                                                                \r\n  "
+ "        {                                                                                                                                       \r\n  "
+ "                                                                                                                                                \r\n  "
+ "            private static global::System.Resources.ResourceManager resourceMan;                                                                \r\n  "
+ "                                                                                                                                                \r\n  "
+ "            private static global::System.Globalization.CultureInfo resourceCulture;                                                            \r\n  "
+ "                                                                                                                                                \r\n  "
+ "            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\")]   \r\n     "
+ "            public " + className + "()                                                                                                                \r\n  "
+ "            {                                                                                                                                   \r\n  "
+ "            }                                                                                                                                   \r\n  "
+ "                                                                                                                                                \r\n  "
+ "            /// <summary>                                                                                                                       \r\n  "
+ "            ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.                           \r\n  "
+ "            /// </summary>                                                                                                                      \r\n  "
+ "            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]               \r\n  "
+ "            public static global::System.Resources.ResourceManager ResourceManager                                                            \r\n  "
+ "            {                                                                                                                                   \r\n  "
+ "                get                                                                                                                             \r\n  "
+ "                {                                                                                                                               \r\n  "
+ "                    if (object.ReferenceEquals(resourceMan, null))                                                                              \r\n  "
+ "                    {                                                                                                                           \r\n  "
+ "                        global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(\"Qlik.Resources." + className + "\", typeof(" + className + ").Assembly);\r\n"
+ "                        resourceMan = temp;                                                                                                      \r\n"
+ "                    }                                                                                                                            \r\n"
+ "                    return resourceMan;                                                                                                          \r\n"
+ "                }                                                                                                                                \r\n"
+ "            }                                                                                                                                    \r\n"
+ "                                                                                                                                                 \r\n"
+ "            /// <summary>                                                                                                                        \r\n"
+ "            ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle                                                   \r\n"
+ "            ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.                                                  \r\n"
+ "            /// </summary>                                                                                                                       \r\n"
+ "            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]                \r\n"
+ "            public static global::System.Globalization.CultureInfo Culture                                                                     \r\n"
+ "            {                                                                                                                                    \r\n"
+ "                get                                                                                                                              \r\n"
+ "                {                                                                                                                                \r\n"
+ "                    return resourceCulture;                                                                                                      \r\n"
+ "                }                                                                                                                                \r\n"
+ "                set                                                                                                                              \r\n"
+ "                {                                                                                                                                \r\n"
+ "                    resourceCulture = value;                                                                                                     \r\n"
+ "                }                                                                                                                                \r\n"
+ "            }";
            tw = File.CreateText(filename);
            tw.Write(startText);
        }

        public void AddResource(string key)
        {
            var varDef =
"            public static string "+key+" {\r\n"
+ "            get {\r\n"
+ "                return ResourceManager.GetString(\""+key+"\", resourceCulture);\r\n"
+ "            }\r\n"
+ "        } \r\n"; 
            tw.Write(varDef);
        }

        public void Dispose()
        {
            var endLines = 
"    }\r\n"
+"}";
            tw.Write(endLines);
            tw.Close();            
        }
    }
}
